ignorePatterns:
  - '*.json'
  - '*.css'
extends:
  - standard
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: 2020
  sourceType: module
  allowImportExportEverywhere: false
env:
  es6: true
  node: true
rules:
  indent:
    - error
    - 4
  no-console: 'off'
  import/extensions: 'off'
  no-underscore-dangle: 'off'
  no-restricted-syntax: 'off'
  no-await-in-loop: 'off'
plugins:
  - standard
  - import
  - prettier
settings:
  react:
    version: detect
